server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /comserv
    path: /rest

logging:
  level:
    root: INFO
    com:
      sb:
        stu: DEBUG
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: TRACE
            mvc:
              method:
                annotation:
                  ServletInvocableHandleMethod: TRACE
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
              BasicExtractor: TRACE
        engine:
          QueryParameters: TRACE
          query:
            HQLQueryPlan: TRACE
  file: log/comserv.log

spring:
  #=====================jpa config================================
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#=====================database config============================
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/information_schema
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


