server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /aoplog
    path: /rest

logging:
  level:
    root: INFO
    com:
      sb:
        stu: DEBUG
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: TRACE
            mvc:
              method:
                annotation:
                  ServletInvocableHandleMethod: TRACE
  file: log/aoplog.log

spring:
  aop:
    auto: true